apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "letsencrypt-issuer.fullname" . }}-letsencrypt-clusterissuer
  labels: {{ include "letsencrypt-issuer.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ printf "letsencrypt-%s-private-key" .Values.environment }}
    server: {{ .Values.issuerUrl | default "https://acme-staging-v02.api.letsencrypt.org/directory" }}
    solvers: {{ required ".Values.solvers must be defined!" .Values.solvers | toYaml | nindent 4 }}
