{{- if and .Values.gotenberg.enabled .Values.gotenberg.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corteza.gotenberg.fullname" . }}
  labels:
    {{- include "corteza.labels" (dict "context" . "component" .Values.gotenberg.name "name" .Values.gotenberg.name) | nindent 4 }}
  {{- with .Values.gotenberg.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
