{{- if .Values.letsencrypt.enabled -}}
{{- $globalScope := . -}}
{{- with .Values.letsencrypt -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
{{ include "corteza-all-in-one.labels" $globalScope | indent 4 }}
spec:
  acme:
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ printf "letsencrypt-%s-private-key" .environment }}
    {{ if .issuerUrl -}}
    server: {{ .issuerUrl }}
    {{- else if (eq .environment "production") -}}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else -}}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    {{ if .solvers -}}
    solvers: {{ .solvers | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
