{{- if and .Values.server.ingress.enabled (eq .Values.server.ingress.controller "gcp") .Values.server.ingress.gcp.backendConfig }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "corteza.server.fullname" . }}
  labels:
    {{- include "corteza.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
{{- with .Values.server.ingress.gcp.backendConfig }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
