{{- if .Values.backup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "postgresql.fullname" . }}-backup
  labels:
    {{- include "postgresql.labels" (dict "context" . "component" "backup") | nindent 4 }}
spec:
  schedule: {{ .Values.backup.schedule | default "*/5 * * * *" | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "postgresql.labels" (dict "context" . "component" "backup") | nindent 12 }}
        spec:
          containers:
            - name: {{ include "postgresql.fullname" . }}-backup
              image: {{ include "postgresql.backupImage" . }}
              imagePullPolicy: {{ .Values.backup.image.pullPolicy | default "IfNotPresent" }}
              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgresql.secretName" . }}
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgresql.secretName" . }}
                      key: password
                - name: PGHOST
                  value: {{ include "postgresql.fullname" . | quote }}
                - name: PGDATABASE
                  value: {{ keys .Values.databases | first | quote }}
                - name: BACKUP_DIR
                  value: {{ required "A mount path must be provided for the backup cronjob!" .Values.backup.mountPath | quote }}
              command: ["/bin/sh", "-c"]
              args:
                - pg_dump --clean --if-exists --load-via-partition-root --quote-all-identifiers --file="${BACKUP_DIR}/pg_dump-$(date '+%Y-%m-%d-%H-%M').sql" $PGDATABASE
              volumeMounts:
                - name: backup
                  mountPath: {{ .Values.backup.mountPath }}
          restartPolicy: OnFailure
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: {{ include "postgresql.backupClaimName" . }}
{{- end -}}
