{{ if .Values.backup.enabled }}
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.backupClaimName" . }}
  labels:
    {{- include "postgresql.labels" (dict "context" . "component" "backup-storage") | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backup.accessMode }}
  resources:
    requests:
        storage: {{ .Values.backup.size }}
  storageClassName: {{ .Values.backup.storageClass | default "" }}
{{- end }}
