{{- if .Values.restore.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "postgresql.fullname" . }}-restore"
  labels:
    {{ include "postgresql.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{ include "postgresql.labels" $ | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-db
          image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
          imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
          command: ['sh', '-c', 'until pg_isready -h $PGHOST -U $PGUSER; do echo waiting; sleep 2; done']
          env:
            - name: PGHOST
              value: {{ include "postgresql.fullname" . | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                    name: {{ printf "%s.%s.credentials.postgresql.acid.zalan.do" "postgres" (include "postgresql.fullname" $) }}
                    key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ printf "%s.%s.credentials.postgresql.acid.zalan.do" "postgres" (include "postgresql.fullname" $) }}
                    key: password
      containers:
        - name: pgrestore
          image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
          imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s.%s.credentials.postgresql.acid.zalan.do" "postgres" (include "postgresql.fullname" $) }}
                  key: password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s.%s.credentials.postgresql.acid.zalan.do" "postgres" (include "postgresql.fullname" $) }}
                  key: username
            - name: PGHOST
              value: {{ include "postgresql.fullname" . | quote }}
            - name: BACKUP_DIR
              value: {{ .Values.backup.mountPath | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "$PGHOST:5432:*:$PGUSER:$PGPASSWORD" > ~/.pgpass
              chmod 600 ~/.pgpass
              psql "postgresql://$PGUSER@$PGHOST:5432/corteza?sslmode=require" --file="$(ls $BACKUP_DIR/pg_dump-*.sql | sort | tail -n 1)"
          volumeMounts:
            - name: backup
              mountPath: {{ .Values.backup.mountPath }}
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.restore.dataSource.claimName | default (printf "%s-backup" (include "postgresql.fullname" $)) }}
      restartPolicy: OnFailure
{{- end -}}