{{- if .Values.server.extraSecret.data -}}
{{- $secretName := printf "corteza-server-%s-extra" (include "corteza.server.fullname" . ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default $secretName .Values.server.extraSecret.name }}
{{- if .Values.server.extraSecret.annotations }}
  annotations:
{{ toYaml .Values.server.extraSecret.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "corteza.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
data:
{{- range $key, $val := .Values.server.extraSecret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
