apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corteza.server.fullname" . }}
  labels:
    {{- include "corteza.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
data:
  db-dsn: {{ include "corteza.dbDsn" . | b64enc }}
