annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: corteza
      image: docker.io/cortezaproject/corteza:2023.9.7
    - name: corredor
      image: docker.io/cortezaproject/corteza-server-corredor:2023.9.2

apiVersion: v2
name: corteza
type: application
version: 1.0.1
appVersion: "2023.9.5"

description: A Helm chart for deploying the Corteza low code platform.
home: https://github.com/origoss/charts

dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 14.x.x

maintainers:
- email: erik.jagyugya@origoss.com
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: kornel.david@origoss.com
  name: davidkornel
  url: https://github.com/davidkornel
- email: david.koterlan@origoss.com
  name: davidkoterlan
  url: https://github.com/davidkoterlan
