name: Kuttl Test

on:
  workflow_dispatch:

jobs:
  kuttl-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This installs the kubectl binary https://github.com/marketplace/actions/kubectl-tool-installer
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4.0.1
        with:
          version: '1.33'

      - name: Set up Krew
        run: >
          set -x; cd "$(mktemp -d)" &&
          OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
          ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
          KREW="krew-${OS}_${ARCH}" &&
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
          tar zxvf "${KREW}.tar.gz" &&
          ./"${KREW}" install krew &&
          echo "PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH" >> "$GITHUB_ENV"

      - name: Set up KUTTL
        run: kubectl-krew install kuttl

      # This installs Helm https://github.com/marketplace/actions/helm-tool-installer
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Run KUTTL tests on Kind
        run: >
          kubectl-kuttl test
          --start-kind
          --config charts/corteza-all-in-one/tests/smoke/standalone-corteza/kuttl-test.yaml

      - name: Set up K3s in docker
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Start K3d cluster
        run: k3d cluster create test

      - name: Run KUTTL tests on K3s
        run: >
          kubectl-kuttl test
          --config charts/corteza-all-in-one/tests/smoke/standalone-corteza/kuttl-test.yaml

      - name: Stop K3d cluster
        run: k3d cluster delete test

      - name: Set up minikube
        uses: medyagh/setup-minikube@v0.0.19
        with:
          start-args: '--wait=all --force -p test'

      - name: Run KUTTL tests on Minikube
        run: >
          kubectl-kuttl test
          --config charts/corteza-all-in-one/tests/smoke/standalone-corteza/kuttl-test.yaml