name: Kuttl Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/corteza/**'
      - '.github/workflows/kuttl-test.yaml'

jobs:
  kuttl-test:
    strategy:
      matrix:
        k8s_env:
          - kind
          - k3s
          - minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This installs the kubectl binary https://github.com/marketplace/actions/kubectl-tool-installer
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4.0.1
        with:
          version: 'v1.33.0'

      - name: Set up Krew
        run: >
          set -x; cd "$(mktemp -d)" &&
          OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
          ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
          KREW="krew-${OS}_${ARCH}" &&
          VERSION="v0.4.5" &&
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${VERSION}/${KREW}.tar.gz" &&
          tar zxvf "${KREW}.tar.gz" &&
          ./"${KREW}" install krew &&
          echo "PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH" >> "$GITHUB_ENV"

      - name: Set up KUTTL
        run: kubectl-krew install kuttl

      # This installs Helm https://github.com/marketplace/actions/helm-tool-installer
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 'v3.17.0'

      - name: Set up Helm repositories
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Build Helm dependencies
        run: helm dep build charts/corteza

      - name: Set up K3s in docker
        if: matrix.k8s_env == 'k3s'
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.8.3 bash

      - name: Start K3d cluster
        if: matrix.k8s_env == 'k3s'
        run: k3d cluster create test

      # This starts a minikube cluster https://github.com/marketplace/actions/setup-minikube
      - name: Set up minikube
        if: matrix.k8s_env == 'minikube'
        uses: medyagh/setup-minikube@v0.0.19
        with:
          cpus: 2
          memory: 2000m
          minikube-version: '1.35.0'

      - name: Run standalone corteza KUTTL tests on Kind
        if: matrix.k8s_env == 'kind'
        run: >
          kubectl-kuttl test
          --start-kind
          --kind-config charts/corteza/tests/smoke/config/kind-config.yaml
          --config charts/corteza/tests/smoke/kuttl-test.yaml

      - name: Run standalone corteza KUTTL tests
        if: matrix.k8s_env != 'kind'
        run: >
          kubectl-kuttl test
          --config charts/corteza/tests/smoke/kuttl-test.yaml
