## This file is used to configure the nginx-ingress-controller helm chart.
## For more information, see https://artifacthub.io/packages/helm/bitnami/nginx-ingress-controller

kind: Deployment

service:
  type: NodePort

ingressClassResource:
  default: true
