# Default values for corteza-all-in-one.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
global:
  domain: &domain "example.com"
# This block is for setting up the ingress for more information can be found here: https://artifacthub.io/packages/helm/bitnami/nginx-ingress-controller
nginx-ingress-controller:
  enabled: true
  kind: Deployment
  service:
    type: NodePort
  ingressClassResource:
    default: true

# This block is for setting up the cert-manager for more information can be found here: https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=install
cert-manager:
  enabled: true
  crds:
    enabled: true

# This block is for setting up the letsencrypt ClusterIssuer
letsencrypt:
  ## @param letsencrypt.enabled Enable the letsencrypt ClusterIssuer
  ##
  enabled: true
  ## @param letsencrypt.environment Environment for the letsencrypt ClusterIssuer. Default is "staging".
  ##
  environment: staging
  ## @param letsencrypt.email Email address for the letsencrypt ClusterIssuer. Letsencrypt sends alerts and notifications to this address.
  ##
  email: igor.turos@origoss.com
  ## @param letsencrypt.issuerUrl URL of the ACME server. If not set, it will default to the production or staging URL based on the environment.
  ##
  issuerUrl: ""
  ## @param letsencrypt.solvers Solvers for the letsencrypt ClusterIssuer.
  ##
  solvers:
    - http01:
        ingress:
          ingressClassName: nginx
    # Uncomment the following lines to use DNS01 solver with Cloudflare
    # - dns01:
    #     cloudflare:
    #       email:

# This block is for setting up the corteza for more information can be found here: https://artifacthub.io/packages/helm/corteza/corteza
corteza:
  corredor:
    enabled: false
  enabled: true
  server:
    image:
      tag: "2024.9.0"
      repository: "cortezaproject/corteza"
    ingress:
      enabled: true
      controller: regular
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
      hosts:
        - host: *domain
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: chart-example-tls
          hosts:
            - *domain
    # extraEnvFrom:
    # - name: DB_DSN
    #   secretRef:
    #     name: db-dsn
    extraEnv:
      - name: HTTP_WEBAPP_ENABLED
        value: "true"
      - name: ACTIONLOG_ENABLED
        value: "false"
